add filters for platform and status, fix typo error
hr3lxphr6j/bililive-go pull request #597
Opened 2023-11-14 14:09 UTC by zS1m

Add filters for platform and status, fix typo error #230 #340

2023-11-20 13:02 UTC, kira1928 requested changes

2023-11-20 13:02 UTC, kira1928 commented on src/webapp/src/component/live-list/index.tsx
> +            }
这里是不小心改掉的吗？
没有特别的理由最好不要局部使用和其他代码不同的代码格式。

2023-11-20 13:02 UTC, kira1928 commented on src/webapp/src/component/live-list/index.tsx
> +                column.filters = list.map(item => ({ text: item.address, value: item.address }));
这里取到的 filters 数组中会包含重复的直播平台名吧？
是不是再过滤一下重复值之后再传给 filters 比较好？

2023-11-20 13:02 UTC, kira1928 commented on src/webapp/src/component/live-list/index.tsx
> +                column.onFilter = (value: string, record: ItemData) => record.address.toLowerCase() === value.toLowerCase();
这些直播平台名是golang程序内部的固定常量，应该不用做 toLowerCase() 处理。保证它们完全一致的责任在 golang 端。

2023-11-20 13:02 UTC, kira1928 commented on src/webapp/src/component/live-list/index.tsx
> +                column.filters = ['初始化', '监控中', '录制中', '已停止'].map((text) => ({ text, value: text }));
这里有一个吹毛求疵的小意见，就是这一行里 `map((text) =>` 部分给参数使用了单独的括号，但上面的 address 列的对应 map 里的参数`item`是省略括号的。这里的格式可以统一一下吗？

2023-11-21 02:23 UTC, zS1m commented on src/webapp/src/component/live-list/index.tsx
> +            }
这里是有意修改的，因为看到上一个对象的render没有添加逗号，columns和smallColumns的最后一个元素后也没有逗号，刚才仔细看了下发现代码格式有些混乱，后面我会添加回来的

2023-11-21 02:25 UTC, zS1m commented on src/webapp/src/component/live-list/index.tsx
> +                column.filters = ['初始化', '监控中', '录制中', '已停止'].map((text) => ({ text, value: text }));
好的，这里我会更改一下

2023-11-21 02:25 UTC, zS1m commented on src/webapp/src/component/live-list/index.tsx
> +                column.onFilter = (value: string, record: ItemData) => record.address.toLowerCase() === value.toLowerCase();
是的，这里我在提交后发现多此一举，本想着跟着下一次pull request一起修改，但是近期身体染病，一直没来得及看，后续我会修改一下

2023-11-21 02:26 UTC, zS1m commented on src/webapp/src/component/live-list/index.tsx
> +                column.filters = list.map(item => ({ text: item.address, value: item.address }));
本地测试的时候确实没考虑到这个问题，我会测试一下重复值是否会有影响

2023-11-21 05:00 UTC, kira1928 commented on src/webapp/src/component/live-list/index.tsx
> +            }
我是看了一下上面和这个修改位置处于同一个数组中的其他元素带逗号，所以觉得保留比较好。

2023-11-21 05:02 UTC, kira1928 commented on src/webapp/src/component/live-list/index.tsx
> +                column.filters = list.map(item => ({ text: item.address, value: item.address }));
也许对功能不会有影响，但可能影响后来者在阅读这段代码时候的理解速度。
不管对功能有没有影响，建议都做一下过滤。或者如果懒得改的话至少留一段注释说明一下这里发生了什么比较好。

2023-11-21 05:03 UTC, kira1928 commented on src/webapp/src/component/live-list/index.tsx
> +                column.onFilter = (value: string, record: ItemData) => record.address.toLowerCase() === value.toLowerCase();
健康第一，这边完全不用着急。毕竟我也没有第一时间review你的修改，你加急改了我压力更大。。

2023-11-23 03:55 UTC, kira1928 approved these changes

2023-11-23 03:59 UTC, merged

2023-11-23 03:59 UTC, kira1928 commented
感谢支援！