fixed: 修复抖音无法获取监控信息的问题
hr3lxphr6j/bililive-go pull request #630
Opened 2023-12-27 11:56 UTC by hucaloof

修复抖音无法获取监控信息的问题

2023-12-27 13:41 UTC, myxingkong commented on src/live/douyin/douyin.go
> +		// requests.Cookies(cookieKVs),
这行其实可以不用屏蔽，只要确保odin_tt的顺序在Cookie的第一个就行。

```Go
resp, err := requests.Get(
		l.Url.String(),
		live.CommonUserAgent,
		requests.Cookies(cookieKVs),
		requests.Headers(map[string]interface{}{
			"Cache-Control": "no-cache",
			"Cookie":        fmt.Sprintf("odin_tt=%s", createRandomOdintt()),
		}),
	)
```

2023-12-27 17:23 UTC, kira1928 requested changes

2023-12-27 17:23 UTC, kira1928 commented on src/live/douyin/douyin.go
> +			"Cookie":        fmt.Sprintf("odin_tt=%s; __ac_nonce=%s", createRandomOdintt(), createRandomCookie()),
这样会覆盖掉配置文件中的 cookie 的。
我给你发了一个 [PR](https://github.com/hucaloof/bililive-go/pull/1) 修复了配置里的 cookie 被覆盖的问题，你看可以的话就 merge 到你的 master 里，然后我这边 merge 你的 PR 好吗？

2023-12-28 04:49 UTC, kira1928 approved these changes

2023-12-28 04:50 UTC, merged