support bilibili audio only record
hr3lxphr6j/bililive-go pull request #679
Opened 2024-02-09 14:50 UTC by ashesofdream

Use android api to support record bilibili live audio stream only. 
Usage:
live_rooms:
- url: https://live.bilibili.com/xxxx
  is_listening: true
  audio_only: true

2024-02-12 13:42 UTC, kira1928 requested changes
主要是对 ffmpeg 的参数改动我比较担心，因为这个影响范围非常大。

2024-02-12 13:42 UTC, kira1928 commented on src/live/consts.go
> +var AndroidBiliAgent = requests.UserAgent(androidBiliAgent)
bilibili 专用的常数就把它移动到 src/live/bilibili/bilibili.go 里吧。

2024-02-12 13:42 UTC, kira1928 commented on src/pkg/parser/ffmpeg/ffmpeg.go
> +		"-y",
这个改动的目的可以解释一下吗？
这个参数好像是让 ffmpeg 按直播速度下载直播流，不要过快请求网络IO，造成不必要的性能浪费。
去掉它是为什么呢？

2024-02-12 13:42 UTC, kira1928 commented on src/pkg/parser/ffmpeg/ffmpeg.go
> -		"-bsf:a", "aac_adtstoasc",
这个改动的目的可以解释一下吗？
[这个参数](https://ffmpeg.org/ffmpeg-bitstream-filters.html#aac_005fadtstoasc)好像是给直播的音频流创建一个配置tag，我不确定去掉它对某些直播网站会不会有影响。

2024-02-12 18:49 UTC, ashesofdream commented on src/pkg/parser/ffmpeg/ffmpeg.go
> -		"-bsf:a", "aac_adtstoasc",
原本一直报403error，debug时删了一些参数，新的commit已经找到问题并还原了。

2024-02-12 18:50 UTC, ashesofdream commented on src/live/consts.go
> +var AndroidBiliAgent = requests.UserAgent(androidBiliAgent)
新的commit已经清除。

2024-02-25 10:25 UTC, kira1928 approved these changes

2024-02-25 10:25 UTC, merged

2024-02-25 10:48 UTC, kira1928 commented
@ashesofdream 
感谢大佬！
还有一个小问题，不是你的问题，但是影响到了你的PR，就是这个新参数和之前的 quality 一样，都不能在程序运行途中修改，就算修改后配置文件保存成功了，也会在开关任意直播间或其他会改变配置内容的操作时因为缓存没有被正确更新而覆盖掉你修改后的那些配置项。
我在本地有一个开发中的 branch 用来修复这个问题，顺便还会把b站专用的 quality 和你这次添加的 audio_only 房间参数改为默认值不会写入 yaml 文件，这样其他直播间的参数不会出现大量无关的这两个参数的默认值项。
在我本地的修复提交之前，暂时不会发布新的 release 版本，所以你的修改内容上线还需要等待一段时间，不好意思。